### ISSUE TITLE
Replace chalk with kleur

### ISSUE THREAD

**Issue by DanielRuf** [runebaas/git-identity#1]
kleur is much faster and smaller. Alternatively the native ASCII color codes can be used.

**Comment by runebaas** [comment]
Hey Daniel, i tried on both windows and linux to see if i could measure any significant difference in speed between using chalk and kleur, but found none. Kleur is however a lot smaller and the underlying code seems less complex, so that's a plus, i swapped it out in 4da43084e347b1962a5505f55a713dbdc8bfff74 and released version 1.1.2 on npm.

Thanks for submitting an issue and using git-identity, i never thought someone would actually use it 🎉
